# Project Name
TARGET = 2CQ

## Comment out for debugging
#LDFLAGS += -u _printf_float

# Sources
CPP_SOURCES = 2CQ.cpp

# Library Locations
LIBDAISY_DIR ?= ../../lib/libDaisy/
DAISYSP_DIR ?= ../../lib/DaisySP/

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
